### PR TITLE
Added dotnet sonar scanner image for scanning dotnet solutions with c…

### PR DESCRIPTION
**Pull request by ianmburns**
…ode coverage

# PR Details

This image contains the .NET 5.0 SDK and installs global dotnet tools for running the sonar scanner with code coverage.

## Description

This image is based off the .NET 5 SDK from the Microsoft registry at mcr.microsoft.com. The dockerfile installs openjdk-11-jdk from apt-get, which is required for sonar scanner. It also installs the dotnet global tooling for sonar-scanner and coverlet from the Microsoft nuget registry.

 See the [SonarScanner for .NET](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-msbuild/) documentation for more details.

## How Has This Been Tested

This docker image has been used with a jenkins pipeline to run static analysis on a dotnet solution. The step was derived from the existing static code analysis with adjustments for the dotnet scanner. The step was able to upload analysis and code coverage to a SonarQube server.

## Types of Changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Review by CSpicer-BAH — APPROVED** [review]
Only requested change would be to include a how-to-use section in the README to let users know of any special requirements needed to run the container. Otherwise, the container seems satisfactory to me and is ready to be merged.

**Comment by CSpicer-BAH** [comment]
Will merge pull request once container functionality testing has finished.

**Comment by cokieffebah** [comment]
@CSpicer-BAH @psig-bah merge when you have run your tests

**Comment by CSpicer-BAH** [comment]
Completed functional testing of the container. No issues found. During testing, needed to install nodejs in the container for testing https://github.com/dotnet/samples code.

**Pull request merged**
